server:
  port: 8094

spring:
  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: companies
      port: 9042
      contact-points: localhost
      schema-action: create_if_not_exists